/**
 * Complete English Phoneme Database
 * 44 phonemes with IPA, colors, descriptions, and examples
 */

import { Phoneme, PhonemeCategory, MouthShape } from '@/types/phonics';

// Short Vowels (5)
const shortVowels: Phoneme[] = [
  {
    id: 'short-a',
    symbol: 'a',
    ipa: '/æ/',
    category: 'short_vowel',
    color: '#FF6B6B',
    description: 'Open your mouth wide. Your tongue is low and flat.',
    tips: ['Say "ah" but shorter', 'Like the "a" in "cat"', 'Keep your mouth wide open'],
    examples: ['cat', 'hat', 'bat', 'man', 'can', 'pan'],
    mouthShape: 'open_wide',
  },
  {
    id: 'short-e',
    symbol: 'e',
    ipa: '/ɛ/',
    category: 'short_vowel',
    color: '#FF6B6B',
    description: 'Open your mouth a little. Your tongue is in the middle.',
    tips: ['Like the "e" in "bed"', 'Not too wide, not too closed', 'Tongue stays relaxed'],
    examples: ['bed', 'red', 'pet', 'hen', 'pen', 'ten'],
    mouthShape: 'open_medium',
  },
  {
    id: 'short-i',
    symbol: 'i',
    ipa: '/ɪ/',
    category: 'short_vowel',
    color: '#FF6B6B',
    description: 'Smile a little. Your tongue is high but relaxed.',
    tips: ['Like the "i" in "sit"', 'A quick, short sound', 'Slight smile position'],
    examples: ['sit', 'bit', 'hit', 'pig', 'big', 'dig'],
    mouthShape: 'open_small',
  },
  {
    id: 'short-o',
    symbol: 'o',
    ipa: '/ɒ/',
    category: 'short_vowel',
    color: '#FF6B6B',
    description: 'Round your lips a little. Your mouth is open.',
    tips: ['Like the "o" in "hot"', 'Round but not too tight', 'Short and quick'],
    examples: ['hot', 'pot', 'dog', 'log', 'mop', 'top'],
    mouthShape: 'rounded_open',
  },
  {
    id: 'short-u',
    symbol: 'u',
    ipa: '/ʌ/',
    category: 'short_vowel',
    color: '#FF6B6B',
    description: 'Relax your mouth. Your tongue is in the middle.',
    tips: ['Like the "u" in "cup"', 'Very relaxed sound', 'Think "uh"'],
    examples: ['cup', 'bus', 'nut', 'sun', 'run', 'fun'],
    mouthShape: 'open_medium',
  },
];

// Long Vowels (5)
const longVowels: Phoneme[] = [
  {
    id: 'long-a',
    symbol: 'a_e',
    ipa: '/eɪ/',
    category: 'long_vowel',
    color: '#4ECDC4',
    description: 'Say the letter name "A". Your mouth moves from open to a smile.',
    tips: ['Say the letter "A"', 'Start with mouth open', 'End with a slight smile'],
    examples: ['cake', 'make', 'rain', 'play', 'day', 'way'],
    mouthShape: 'closed_smile',
  },
  {
    id: 'long-e',
    symbol: 'ee',
    ipa: '/iː/',
    category: 'long_vowel',
    color: '#4ECDC4',
    description: 'Smile wide! Your tongue is high in your mouth.',
    tips: ['Say the letter "E"', 'Big smile', 'Hold it longer than short e'],
    examples: ['bee', 'see', 'tree', 'feet', 'meat', 'seat'],
    mouthShape: 'closed_smile',
  },
  {
    id: 'long-i',
    symbol: 'i_e',
    ipa: '/aɪ/',
    category: 'long_vowel',
    color: '#4ECDC4',
    description: 'Start with mouth open, end with a smile. Say the letter "I".',
    tips: ['Say the letter "I"', 'Start open, end closed', 'Two sounds together'],
    examples: ['bike', 'like', 'time', 'five', 'kite', 'ride'],
    mouthShape: 'open_wide',
  },
  {
    id: 'long-o',
    symbol: 'o_e',
    ipa: '/oʊ/',
    category: 'long_vowel',
    color: '#4ECDC4',
    description: 'Round your lips and say the letter "O".',
    tips: ['Say the letter "O"', 'Start rounded, end more rounded', 'Lips push forward'],
    examples: ['bone', 'home', 'rope', 'boat', 'coat', 'road'],
    mouthShape: 'rounded_open',
  },
  {
    id: 'long-u',
    symbol: 'u_e',
    ipa: '/uː/',
    category: 'long_vowel',
    color: '#4ECDC4',
    description: 'Round your lips tightly and say "oo".',
    tips: ['Say "oo" like in "moon"', 'Very round lips', 'Push lips forward'],
    examples: ['tube', 'cube', 'blue', 'glue', 'moon', 'food'],
    mouthShape: 'rounded_small',
  },
];

// Consonants (21)
const consonants: Phoneme[] = [
  {
    id: 'b',
    symbol: 'b',
    ipa: '/b/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Press your lips together, then let air burst out with your voice.',
    tips: ['Lips together then apart', 'Feel your throat vibrate', 'Quick burst of air'],
    examples: ['bat', 'boy', 'ball', 'baby', 'book', 'bird'],
    mouthShape: 'lips_together',
  },
  {
    id: 'c-k',
    symbol: 'c/k',
    ipa: '/k/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Push air from the back of your throat. No voice.',
    tips: ['Back of tongue touches roof', 'Quick release of air', 'No vibration in throat'],
    examples: ['cat', 'kite', 'cake', 'king', 'duck', 'back'],
    mouthShape: 'tongue_back',
  },
  {
    id: 'd',
    symbol: 'd',
    ipa: '/d/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Touch your tongue behind your top teeth, then let air burst out with voice.',
    tips: ['Tongue tip behind top teeth', 'Feel throat vibrate', 'Quick tap'],
    examples: ['dog', 'dad', 'door', 'day', 'bed', 'red'],
    mouthShape: 'tongue_ridge',
  },
  {
    id: 'f',
    symbol: 'f',
    ipa: '/f/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Gently bite your bottom lip and blow air through.',
    tips: ['Top teeth on bottom lip', 'Blow air through', 'No voice'],
    examples: ['fan', 'fish', 'fun', 'five', 'leaf', 'off'],
    mouthShape: 'teeth_lip',
  },
  {
    id: 'g',
    symbol: 'g',
    ipa: '/ɡ/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Push air from the back of your throat with your voice.',
    tips: ['Like /k/ but with voice', 'Feel throat vibrate', 'Back of tongue up'],
    examples: ['go', 'get', 'game', 'girl', 'dog', 'big'],
    mouthShape: 'tongue_back',
  },
  {
    id: 'h',
    symbol: 'h',
    ipa: '/h/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Just breathe out! Like you\'re fogging up a window.',
    tips: ['Just a breath out', 'Mouth relaxed', 'Very soft sound'],
    examples: ['hat', 'hot', 'house', 'happy', 'hello', 'hill'],
    mouthShape: 'neutral',
  },
  {
    id: 'j',
    symbol: 'j',
    ipa: '/dʒ/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Touch the roof of your mouth with your tongue and say "j" with voice.',
    tips: ['Like "ch" but with voice', 'Tongue on roof then release', 'Feel vibration'],
    examples: ['jam', 'jet', 'jump', 'jog', 'job', 'jar'],
    mouthShape: 'fricative',
  },
  {
    id: 'l',
    symbol: 'l',
    ipa: '/l/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Touch your tongue behind your top teeth and let air flow around it.',
    tips: ['Tongue tip up behind teeth', 'Air goes around tongue', 'Voiced sound'],
    examples: ['leg', 'lamp', 'like', 'love', 'ball', 'tell'],
    mouthShape: 'tongue_ridge',
  },
  {
    id: 'm',
    symbol: 'm',
    ipa: '/m/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Press your lips together and hum.',
    tips: ['Lips together', 'Sound comes through nose', 'Feel lips vibrate'],
    examples: ['mom', 'man', 'map', 'milk', 'home', 'jam'],
    mouthShape: 'lips_together',
  },
  {
    id: 'n',
    symbol: 'n',
    ipa: '/n/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Touch your tongue behind your top teeth and hum.',
    tips: ['Tongue behind top teeth', 'Sound through nose', 'Like humming'],
    examples: ['no', 'net', 'nose', 'nine', 'sun', 'pen'],
    mouthShape: 'tongue_ridge',
  },
  {
    id: 'p',
    symbol: 'p',
    ipa: '/p/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Press your lips together, then pop them open with air.',
    tips: ['Lips together then apart', 'Puff of air', 'No voice'],
    examples: ['pan', 'pet', 'pig', 'pop', 'cup', 'tap'],
    mouthShape: 'lips_together',
  },
  {
    id: 'r',
    symbol: 'r',
    ipa: '/r/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Curl your tongue back slightly. Don\'t let it touch anything!',
    tips: ['Tongue curled back', 'Doesn\'t touch roof', 'Round your lips slightly'],
    examples: ['red', 'run', 'rain', 'road', 'car', 'star'],
    mouthShape: 'neutral',
  },
  {
    id: 's',
    symbol: 's',
    ipa: '/s/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Put your teeth together and blow air through. Like a snake!',
    tips: ['Teeth close together', 'Air hisses through', 'No voice'],
    examples: ['sun', 'sit', 'see', 'bus', 'yes', 'miss'],
    mouthShape: 'fricative',
  },
  {
    id: 't',
    symbol: 't',
    ipa: '/t/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Touch your tongue behind your top teeth, then quickly tap it down.',
    tips: ['Tongue behind top teeth', 'Quick tap down', 'Puff of air, no voice'],
    examples: ['top', 'ten', 'time', 'cat', 'hot', 'sit'],
    mouthShape: 'tongue_ridge',
  },
  {
    id: 'v',
    symbol: 'v',
    ipa: '/v/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Gently bite your bottom lip and blow air through with your voice.',
    tips: ['Like /f/ but with voice', 'Top teeth on bottom lip', 'Feel vibration'],
    examples: ['van', 'vine', 'very', 'love', 'have', 'give'],
    mouthShape: 'teeth_lip',
  },
  {
    id: 'w',
    symbol: 'w',
    ipa: '/w/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Round your lips tight like saying "oo", then open them.',
    tips: ['Start with round lips', 'Quickly open to next sound', 'Voiced'],
    examples: ['win', 'wet', 'will', 'wow', 'away', 'swim'],
    mouthShape: 'lips_rounded',
  },
  {
    id: 'x',
    symbol: 'x',
    ipa: '/ks/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Say /k/ quickly followed by /s/.',
    tips: ['Two sounds together', '/k/ then /s/', 'Quick combination'],
    examples: ['box', 'fox', 'six', 'mix', 'fix', 'wax'],
    mouthShape: 'fricative',
  },
  {
    id: 'y',
    symbol: 'y',
    ipa: '/j/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Like you\'re starting to say "ee" but move to the next sound.',
    tips: ['Tongue high, like "ee"', 'Quickly glide to next sound', 'Voiced'],
    examples: ['yes', 'you', 'yell', 'yawn', 'yellow', 'yummy'],
    mouthShape: 'closed_smile',
  },
  {
    id: 'z',
    symbol: 'z',
    ipa: '/z/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Like a buzzing bee! Teeth together, blow air with voice.',
    tips: ['Like /s/ but with voice', 'Buzz like a bee', 'Feel vibration'],
    examples: ['zoo', 'zip', 'zero', 'buzz', 'maze', 'fizz'],
    mouthShape: 'fricative',
  },
  {
    id: 'qu',
    symbol: 'qu',
    ipa: '/kw/',
    category: 'consonant',
    color: '#45B7D1',
    description: 'Say /k/ quickly followed by /w/.',
    tips: ['/k/ and /w/ together', 'Quick combination', 'Lips round for /w/'],
    examples: ['queen', 'quick', 'quit', 'quiz', 'quack', 'quest'],
    mouthShape: 'lips_rounded',
  },
];

// Digraphs (7)
const digraphs: Phoneme[] = [
  {
    id: 'sh',
    symbol: 'sh',
    ipa: '/ʃ/',
    category: 'digraph',
    color: '#96CEB4',
    description: 'Push your lips forward and blow air through. "Shh, be quiet!"',
    tips: ['Lips pushed forward', 'Blow air through', 'No voice'],
    examples: ['ship', 'shop', 'fish', 'wish', 'cash', 'shell'],
    mouthShape: 'fricative',
  },
  {
    id: 'ch',
    symbol: 'ch',
    ipa: '/tʃ/',
    category: 'digraph',
    color: '#96CEB4',
    description: 'Start with /t/ and end with /sh/. Like a train: "choo choo!"',
    tips: ['Starts like /t/', 'Ends like "sh"', 'Quick combination'],
    examples: ['chip', 'chat', 'rich', 'much', 'lunch', 'church'],
    mouthShape: 'fricative',
  },
  {
    id: 'th-voiced',
    symbol: 'th',
    ipa: '/ð/',
    category: 'digraph',
    color: '#96CEB4',
    description: 'Put your tongue between your teeth and blow air with voice.',
    tips: ['Tongue between teeth', 'Blow air with voice', 'Feel vibration'],
    examples: ['the', 'this', 'that', 'them', 'then', 'other'],
    mouthShape: 'tongue_teeth',
  },
  {
    id: 'th-unvoiced',
    symbol: 'th',
    ipa: '/θ/',
    category: 'digraph',
    color: '#96CEB4',
    description: 'Put your tongue between your teeth and blow air. No voice.',
    tips: ['Tongue between teeth', 'Blow air through', 'No vibration'],
    examples: ['think', 'thing', 'bath', 'math', 'tooth', 'three'],
    mouthShape: 'tongue_teeth',
  },
  {
    id: 'wh',
    symbol: 'wh',
    ipa: '/w/',
    category: 'digraph',
    color: '#96CEB4',
    description: 'Round your lips and blow a little air, then open.',
    tips: ['Like /w/', 'Some people add a puff', 'Lips round'],
    examples: ['what', 'when', 'where', 'why', 'white', 'wheel'],
    mouthShape: 'lips_rounded',
  },
  {
    id: 'ph',
    symbol: 'ph',
    ipa: '/f/',
    category: 'digraph',
    color: '#96CEB4',
    description: 'Makes the same sound as "f". Top teeth on bottom lip.',
    tips: ['Same as /f/', 'Top teeth on bottom lip', 'Blow air through'],
    examples: ['phone', 'photo', 'graph', 'dolphin', 'elephant', 'alphabet'],
    mouthShape: 'teeth_lip',
  },
  {
    id: 'ng',
    symbol: 'ng',
    ipa: '/ŋ/',
    category: 'digraph',
    color: '#96CEB4',
    description: 'Push the back of your tongue up and hum through your nose.',
    tips: ['Back of tongue up', 'Sound through nose', 'Like humming'],
    examples: ['ring', 'sing', 'king', 'long', 'song', 'thing'],
    mouthShape: 'tongue_back',
  },
];

// R-Controlled Vowels (5)
const rControlled: Phoneme[] = [
  {
    id: 'ar',
    symbol: 'ar',
    ipa: '/ɑr/',
    category: 'r_controlled',
    color: '#F39C12',
    description: 'Open your mouth and say "ah" with an "r" at the end.',
    tips: ['Start with open mouth', 'Add the "r" sound', 'Tongue curls back'],
    examples: ['car', 'star', 'park', 'farm', 'arm', 'art'],
    mouthShape: 'open_wide',
  },
  {
    id: 'er',
    symbol: 'er',
    ipa: '/ɜr/',
    category: 'r_controlled',
    color: '#F39C12',
    description: 'Say "er" like when you\'re thinking. Tongue curls back.',
    tips: ['Relaxed "er" sound', 'Tongue curled back', 'Very common ending'],
    examples: ['her', 'fern', 'term', 'herd', 'verb', 'perch'],
    mouthShape: 'neutral',
  },
  {
    id: 'ir',
    symbol: 'ir',
    ipa: '/ɜr/',
    category: 'r_controlled',
    color: '#F39C12',
    description: 'Same sound as "er". Tongue curls back.',
    tips: ['Same as "er" sound', 'Tongue curled back', 'Sounds like "ur"'],
    examples: ['bird', 'girl', 'first', 'shirt', 'third', 'dirt'],
    mouthShape: 'neutral',
  },
  {
    id: 'or',
    symbol: 'or',
    ipa: '/ɔr/',
    category: 'r_controlled',
    color: '#F39C12',
    description: 'Round your lips, say "or". Tongue curls back at the end.',
    tips: ['Rounded lips', 'Open mouth', 'Add "r" at end'],
    examples: ['for', 'door', 'more', 'store', 'corn', 'horn'],
    mouthShape: 'rounded_open',
  },
  {
    id: 'ur',
    symbol: 'ur',
    ipa: '/ɜr/',
    category: 'r_controlled',
    color: '#F39C12',
    description: 'Same sound as "er" and "ir". Tongue curls back.',
    tips: ['Same as "er"/"ir"', 'Tongue curled back', 'Think "urrr"'],
    examples: ['fur', 'turn', 'burn', 'hurt', 'nurse', 'purse'],
    mouthShape: 'neutral',
  },
];

// Diphthongs (3)
const diphthongs: Phoneme[] = [
  {
    id: 'oi',
    symbol: 'oi/oy',
    ipa: '/ɔɪ/',
    category: 'diphthong',
    color: '#DDA0DD',
    description: 'Start with mouth round, end with a smile. "Oi!"',
    tips: ['Start round like "o"', 'Glide to "ee"', 'Two sounds together'],
    examples: ['oil', 'coin', 'boy', 'toy', 'joy', 'noise'],
    mouthShape: 'rounded_open',
  },
  {
    id: 'ou',
    symbol: 'ou/ow',
    ipa: '/aʊ/',
    category: 'diphthong',
    color: '#DDA0DD',
    description: 'Start with mouth open, end with lips round. "Ow!"',
    tips: ['Start open like "ah"', 'Glide to "oo"', 'Like saying "ouch"'],
    examples: ['out', 'house', 'cow', 'now', 'how', 'brown'],
    mouthShape: 'open_wide',
  },
  {
    id: 'oo-long',
    symbol: 'oo',
    ipa: '/uː/',
    category: 'diphthong',
    color: '#DDA0DD',
    description: 'Round your lips tightly and say "oo".',
    tips: ['Lips very round', 'Push forward', 'Like a ghost: "ooo"'],
    examples: ['moon', 'food', 'cool', 'school', 'zoo', 'room'],
    mouthShape: 'rounded_small',
  },
];

// Blends (for Level 2) - initial consonant blends
export const INITIAL_BLENDS: Phoneme[] = [
  {
    id: 'bl',
    symbol: 'bl',
    ipa: '/bl/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /b/ and /l/ together quickly.',
    tips: ['/b/ then /l/', 'Blend them smoothly', 'Don\'t add a vowel between'],
    examples: ['blue', 'black', 'blend', 'block', 'blow', 'blade'],
    mouthShape: 'lips_together',
  },
  {
    id: 'cl',
    symbol: 'cl',
    ipa: '/kl/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /k/ and /l/ together quickly.',
    tips: ['/k/ then /l/', 'Smooth transition', 'Quick combination'],
    examples: ['clap', 'class', 'clean', 'clock', 'cloud', 'club'],
    mouthShape: 'tongue_back',
  },
  {
    id: 'fl',
    symbol: 'fl',
    ipa: '/fl/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /f/ and /l/ together quickly.',
    tips: ['/f/ then /l/', 'Lips to tongue', 'Smooth blend'],
    examples: ['flag', 'flat', 'flip', 'floor', 'flower', 'fly'],
    mouthShape: 'teeth_lip',
  },
  {
    id: 'gl',
    symbol: 'gl',
    ipa: '/ɡl/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /g/ and /l/ together quickly.',
    tips: ['/g/ then /l/', 'Back of throat to tongue tip', 'Quick blend'],
    examples: ['glad', 'glass', 'glue', 'glow', 'globe', 'glove'],
    mouthShape: 'tongue_back',
  },
  {
    id: 'pl',
    symbol: 'pl',
    ipa: '/pl/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /p/ and /l/ together quickly.',
    tips: ['/p/ then /l/', 'Pop lips then tongue up', 'No vowel between'],
    examples: ['plan', 'play', 'please', 'plate', 'plus', 'plant'],
    mouthShape: 'lips_together',
  },
  {
    id: 'sl',
    symbol: 'sl',
    ipa: '/sl/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /s/ and /l/ together quickly.',
    tips: ['/s/ then /l/', 'Hiss then tongue up', 'Smooth blend'],
    examples: ['slip', 'slow', 'sleep', 'slide', 'slim', 'sled'],
    mouthShape: 'fricative',
  },
  {
    id: 'br',
    symbol: 'br',
    ipa: '/br/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /b/ and /r/ together quickly.',
    tips: ['/b/ then /r/', 'Lips pop then tongue curls', 'Quick blend'],
    examples: ['brown', 'bread', 'bring', 'bright', 'brush', 'brave'],
    mouthShape: 'lips_together',
  },
  {
    id: 'cr',
    symbol: 'cr',
    ipa: '/kr/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /k/ and /r/ together quickly.',
    tips: ['/k/ then /r/', 'Back of throat then tongue curls', 'Smooth'],
    examples: ['cry', 'crab', 'cream', 'cross', 'crowd', 'crown'],
    mouthShape: 'tongue_back',
  },
  {
    id: 'dr',
    symbol: 'dr',
    ipa: '/dr/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /d/ and /r/ together quickly.',
    tips: ['/d/ then /r/', 'Tongue tap then curl', 'Quick blend'],
    examples: ['drum', 'drop', 'draw', 'drink', 'dress', 'dream'],
    mouthShape: 'tongue_ridge',
  },
  {
    id: 'fr',
    symbol: 'fr',
    ipa: '/fr/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /f/ and /r/ together quickly.',
    tips: ['/f/ then /r/', 'Teeth on lip then tongue curls', 'Smooth'],
    examples: ['frog', 'from', 'free', 'fresh', 'friend', 'fruit'],
    mouthShape: 'teeth_lip',
  },
  {
    id: 'gr',
    symbol: 'gr',
    ipa: '/ɡr/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /g/ and /r/ together quickly.',
    tips: ['/g/ then /r/', 'Back of throat then tongue curls', 'Blend smoothly'],
    examples: ['green', 'grow', 'great', 'grape', 'grass', 'grab'],
    mouthShape: 'tongue_back',
  },
  {
    id: 'pr',
    symbol: 'pr',
    ipa: '/pr/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /p/ and /r/ together quickly.',
    tips: ['/p/ then /r/', 'Lips pop then tongue curls', 'Quick'],
    examples: ['print', 'price', 'proud', 'pretty', 'prize', 'press'],
    mouthShape: 'lips_together',
  },
  {
    id: 'tr',
    symbol: 'tr',
    ipa: '/tr/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /t/ and /r/ together quickly.',
    tips: ['/t/ then /r/', 'Tongue tap then curl', 'Common blend'],
    examples: ['tree', 'train', 'true', 'try', 'trip', 'trick'],
    mouthShape: 'tongue_ridge',
  },
  {
    id: 'st',
    symbol: 'st',
    ipa: '/st/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /s/ and /t/ together quickly.',
    tips: ['/s/ then /t/', 'Hiss then tongue tap', 'Very common'],
    examples: ['stop', 'star', 'stay', 'step', 'stone', 'store'],
    mouthShape: 'fricative',
  },
  {
    id: 'sc-sk',
    symbol: 'sc/sk',
    ipa: '/sk/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /s/ and /k/ together quickly.',
    tips: ['/s/ then /k/', 'Hiss then back of throat', 'Two spellings'],
    examples: ['skip', 'skin', 'sky', 'scare', 'scale', 'score'],
    mouthShape: 'fricative',
  },
  {
    id: 'sm',
    symbol: 'sm',
    ipa: '/sm/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /s/ and /m/ together quickly.',
    tips: ['/s/ then /m/', 'Hiss then hum', 'Blend smoothly'],
    examples: ['small', 'smart', 'smell', 'smile', 'smoke', 'smooth'],
    mouthShape: 'fricative',
  },
  {
    id: 'sn',
    symbol: 'sn',
    ipa: '/sn/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /s/ and /n/ together quickly.',
    tips: ['/s/ then /n/', 'Hiss then hum through nose', 'Quick transition'],
    examples: ['snap', 'snack', 'snake', 'snow', 'snail', 'snore'],
    mouthShape: 'fricative',
  },
  {
    id: 'sp',
    symbol: 'sp',
    ipa: '/sp/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /s/ and /p/ together quickly.',
    tips: ['/s/ then /p/', 'Hiss then lips pop', 'Common blend'],
    examples: ['spin', 'spot', 'spell', 'speak', 'space', 'sport'],
    mouthShape: 'fricative',
  },
  {
    id: 'sw',
    symbol: 'sw',
    ipa: '/sw/',
    category: 'blend',
    color: '#FFEAA7',
    description: 'Say /s/ and /w/ together quickly.',
    tips: ['/s/ then /w/', 'Hiss then round lips', 'Smooth blend'],
    examples: ['swim', 'swing', 'sweet', 'switch', 'swan', 'sweep'],
    mouthShape: 'fricative',
  },
];

// Combine all phonemes
export const ALL_PHONEMES: Phoneme[] = [
  ...shortVowels,
  ...longVowels,
  ...consonants,
  ...digraphs,
  ...rControlled,
  ...diphthongs,
];

// Export by category for easy access
export const PHONEMES_BY_CATEGORY: Record<PhonemeCategory, Phoneme[]> = {
  short_vowel: shortVowels,
  long_vowel: longVowels,
  consonant: consonants,
  digraph: digraphs,
  r_controlled: rControlled,
  diphthong: diphthongs,
  blend: INITIAL_BLENDS,
};

// Quick lookup by ID
export const PHONEME_MAP: Record<string, Phoneme> = Object.fromEntries(
  [...ALL_PHONEMES, ...INITIAL_BLENDS].map((p) => [p.id, p])
);

// Get phoneme by ID
export function getPhoneme(id: string): Phoneme | undefined {
  return PHONEME_MAP[id];
}

// Get all phonemes for a category
export function getPhonemesByCategory(category: PhonemeCategory): Phoneme[] {
  return PHONEMES_BY_CATEGORY[category] || [];
}
